name: CI

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  RUN_NUMBER: ${{ github.run_number }}
  RUN_ATTEMPT: ${{ github.run_attempt }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build Flask application
        run: |
          pyinstaller --hidden-import=flask --hidden-import=requests --hidden-import=urllib3==1.26.6 -w -F --add-data "templates:templates" dict_flask.py
        working-directory: ${{ github.workspace }}

      - name: Build Docker image
        run: |
          docker build -t dockerhub-username/dictionary-app:latest -t dockerhub-username/dictionary-app:${{ env.RUN_NUMBER }}_${{ env.RUN_ATTEMPT }} -f Dockerfile .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push dockerhub-username/dictionary-app:latest
          docker push dockerhub-username/dictionary-app:${{ env.RUN_NUMBER }}_${{ env.RUN_ATTEMPT }}
        
        working-directory: ${{ github.workspace }}
